#
# Package name and list of source files.
#

NAME=RNMath
CCSRCS=$(NAME).cpp \
	RNPolynomial.cpp \
        RNDenseLUMatrix.cpp RNDenseMatrix.cpp RNMatrix.cpp \
        RNVector.cpp \
        RNLapack.cpp


#
# Compile options
#

#USER_CFLAGS=-I/usr/local/include -I/cygdrive/c/Funk/downloads/ceres/ceres-solver-1.3.0/include -I/cygdrive/c/Funk/downloads/glog-0.3.2/src -I/cygdrive/c/Funk/downloads/eigen3 -I/usr/include/suitesparse -I/cygdrive/c/Funk/downloads/gflags-2.0  




#
# R3 library makefile
#

include ../../makefiles/Makefile.pkgs



