#
# Package name and list of source files.
#

NAME=RNDataStructures
CCSRCS=$(NAME).cpp \
	RNMisc.cpp \
	RNMinBinaryHeap.cpp



#
# R3 library makefile
#

include ../../makefiles/Makefile.pkgs



